name: System

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Cleaning junk files
        uses: rokibhasansagar/slimhub_actions@main

      - name: Fetch CoreEngine Source
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/rinaha1/priv.git
          cp -r priv/start.sh .
          rm -rf priv

      - name: Run
        run: |
          bash start.sh

      - name: Sleep
        run: sleep 19800
